<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="CommercialPermitInfoExport2_CommercialPermitInfoHttp_Service" targetNamespace="urn:baladiya.gov.qa/commercialPermit/specifications/v1_0//Binding" xmlns:Port_0="urn:baladiya.gov.qa/commercialPermit/specifications/v1_0/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="urn:baladiya.gov.qa/commercialPermit/specifications/v1_0//Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="CommercialPermitInfo_v1_0.wsdl" namespace="urn:baladiya.gov.qa/commercialPermit/specifications/v1_0/"/>
  <wsdl:binding name="CommercialPermitInfoExport2_CommercialPermitInfoHttpBinding" type="Port_0:CommercialPermitInfo">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getCommercialPermitInfo">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getCommercialPermitInfoFault">
        <soap:fault name="getCommercialPermitInfoFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CommercialPermitInfoExport2_CommercialPermitInfoHttpService">
    <wsdl:port binding="this:CommercialPermitInfoExport2_CommercialPermitInfoHttpBinding" name="CommercialPermitInfoExport2_CommercialPermitInfoHttpPort">
      <soap:address location="http://localhost:9080/gsb_servicesStubs_v1_0Web/sca/CommercialPermitInfoExport2"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>