/**
 * Interface IProcessConstants
 * This interface is listing the keys existing to process resource bundle
 * @author Tlatif
 * @copyright (C) GBM/ictQATAR 2010
 * @date 21.03.2010
 * @history 
 */
package qa.gov.mol.lr.process.constants;

public interface IProcessConstants {
	public static final String PROCESS_CONFIG = "qa/gov/mol/lr/process/config/ProcessConfig";
	public static final String NOTIFICATION_LANG = "NOTIFICATION_LANG";
	public static final String SEND_SMS = "SEND_SMS";
	public static final String NEW_APP_NOTIFICATION_SUBJECT_EN = "NEW_APP_NOTIFICATION_SUBJECT_EN";
	public static final String NEW_APP_NOTIFICATION_SUBJECT_AR = "NEW_APP_NOTIFICATION_SUBJECT_AR";
	public static final String NEW_APP_NOTIFICATION_BODY_EN_EMAIL = "NEW_APP_NOTIFICATION_BODY_EN_EMAIL";
	public static final String NEW_APP_NOTIFICATION_BODY_EN_SMS = "NEW_APP_NOTIFICATION_BODY_EN_SMS";
	public static final String NEW_APP_NOTIFICATION_BODY_AR_EMAIL = "NEW_APP_NOTIFICATION_BODY_AR_EMAIL";
	public static final String NEW_APP_NOTIFICATION_BODY_AR_SMS = "NEW_APP_NOTIFICATION_BODY_AR_SMS";
	public static final String REVIEW_APP_NOTIFICATION_SUBJECT_EN = "REVIEW_APP_NOTIFICATION_SUBJECT_EN";
	public static final String REVIEW_APP_NOTIFICATION_SUBJECT_AR = "REVIEW_APP_NOTIFICATION_SUBJECT_AR";
	public static final String REVIEW_APP_NOTIFICATION_BODY_EN_APPROVED = "REVIEW_APP_NOTIFICATION_BODY_EN_APPROVED";
	public static final String REVIEW_APP_NOTIFICATION_BODY_AR_APPROVED = "REVIEW_APP_NOTIFICATION_BODY_AR_APPROVED";
	public static final String REVIEW_APP_NOTIFICATION_BODY_EN_REJECTED = "REVIEW_APP_NOTIFICATION_BODY_EN_REJECTED";
	public static final String REVIEW_APP_NOTIFICATION_BODY_AR_REJECTED = "REVIEW_APP_NOTIFICATION_BODY_AR_REJECTED";
	public static final String REVIEW_APP_NOTIFICATION_BODY_EN_SUSPENDED = "REVIEW_APP_NOTIFICATION_BODY_EN_SUSPENDED";
	public static final String REVIEW_APP_NOTIFICATION_BODY_AR_SUSPENDED = "REVIEW_APP_NOTIFICATION_BODY_AR_SUSPENDED";
	public static final String REVIEW_APP_ESCALATION_SUBJECT_EN = "REVIEW_APP_ESCALATION_SUBJECT_EN";
	public static final String REVIEW_APP_ESCALATION_SUBJECT_AR = "REVIEW_APP_ESCALATION_SUBJECT_AR";
	public static final String REVIEW_APP_ESCALATION_BODY_EN = "REVIEW_APP_ESCALATION_BODY_EN";
	public static final String REVIEW_APP_ESCALATION_BODY_AR = "REVIEW_APP_ESCALATION_BODY_AR";
	public static final String REVIEW_APP_ESCALATION_DURATION = "REVIEW_APP_ESCALATION_DURATION";
	
	
}
