<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_4.map" md5sum="b0155707b5a397476e4fb53ff911f483" version="6.2.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V6.2.200
*
*   Mapping file:		XSLTransformation1_req_4.map
*   Map declaration(s):	XSLTransformation1_req_4
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amoi.gov.qa%252FestablishmentInfo%252Fspecifications%252Fv1_0%252F%257DEstablishmentSecurityInfogetEstablishmentInfoByIdRequest/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amoi.gov.qa%252FestablishmentInfo%252Fspecifications%252Fv1_0%252F%257DEstablishmentSecurityInfogetEstablishmentInfoByIdResponse/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:io3="wsdl.urn:moi.gov.qa/establishmentInfo/specifications/v1_0/"
    xmlns:io2="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="urn:moi.gov.qa/establishmentInfo/xml/schemas/v1_0/"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="urn:moi.gov.qa/establishmentInfo/specifications/v1_0/"
    xmlns:io7="http://www.w3.org/2005/08/addressing"
    xmlns:io9="urn:igov.gov.qa/commonTypes/xml/schemas/v1_0/"
    xmlns:io10="urn:igov.gov.qa/xml/schemas/v1_0/"
    exclude-result-prefixes="xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="io:smo" mode="XSLTransformation1_req_4"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "io:smo" to "io:smo".  -->
  <xsl:template match="io:smo"  mode="XSLTransformation1_req_4">
    <io:smo>
      <body>
        <io8:EstablishmentSecurityInfogetEstablishmentInfoByIdResponse1>
          <io8:establishmentInfo>
            <!-- a simple mapping with no associated source:  to "io4:name"(string) -->
            <io4:name>
              <xsl:text>المانع جروب</xsl:text>
            </io4:name>
            <!-- a simple mapping with no associated source:  to "io4:specialization"(string) -->
            <io4:specialization>
              <xsl:text>everything</xsl:text>
            </io4:specialization>
            <!-- a simple data mapping: "body/io8:EstablishmentSecurityInfogetEstablishmentInfoByIdRequest1/io8:estId"(EstablishmentIdType) to "io4:Id"(EstablishmentIdType) -->
            <io4:Id>
              <xsl:value-of select="body/io8:EstablishmentSecurityInfogetEstablishmentInfoByIdRequest1/io8:estId"/>
            </io4:Id>
            <io4:address>
              <!-- a simple mapping with no associated source:  to "io9:poBox"(POBoxType) -->
              <io9:poBox>
                <xsl:text>32421</xsl:text>
              </io9:poBox>
            </io4:address>
            <!-- a simple mapping with no associated source:  to "io4:phone"(TelephoneNumberType) -->
            <io4:phone>
              <xsl:text>32141321</xsl:text>
            </io4:phone>
            <io4:owners>
              <!-- a simple mapping with no associated source:  to "io9:qID"(QIdType) -->
              <io9:qID>
                <xsl:text>null</xsl:text>
              </io9:qID>
              <!-- a simple mapping with no associated source:  to "io9:emailAddress"(EmailAddressType) -->
              <io9:emailAddress>
                <xsl:text>owner@hotmail.com</xsl:text>
              </io9:emailAddress>
              <io9:nationality>
                <!-- a simple mapping with no associated source:  to "io9:name_En"(string) -->
                <io9:name_En>
                  <xsl:text>egyption</xsl:text>
                </io9:name_En>
                <!-- a simple mapping with no associated source:  to "io9:ID"(IdType) -->
                <io9:ID>
                  <xsl:text>12321</xsl:text>
                </io9:ID>
              </io9:nationality>
              <io9:profession>
                <!-- a simple mapping with no associated source:  to "io9:name_En"(string) -->
                <io9:name_En>
                  <xsl:text>Engineer</xsl:text>
                </io9:name_En>
                <!-- a simple mapping with no associated source:  to "io9:ID"(IdType) -->
                <io9:ID>
                  <xsl:text>21321</xsl:text>
                </io9:ID>
              </io9:profession>
            </io4:owners>
            <io4:agents>
              <!-- a simple mapping with no associated source:  to "io9:qID"(QIdType) -->
              <io9:qID>
                <xsl:text>321321</xsl:text>
              </io9:qID>
            </io4:agents>
          </io8:establishmentInfo>
        </io8:EstablishmentSecurityInfogetEstablishmentInfoByIdResponse1>
      </body>
    </io:smo>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
