<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_13.map" md5sum="89f4cfb92c17c64b7ab88072c8ede513" version="6.2.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V6.2.200
*
*   Mapping file:		XSLTransformation1_req_13.map
*   Map declaration(s):	XSLTransformation1_req_13
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amol.gov.qa%252FcustomerService%252Frecruitment%252Fspecifications%252Fv1_0%252F%257DActiveLaborRecruitmentApplicationInfogetActiveApplicationByEstIdRequest/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amol.gov.qa%252FcustomerService%252Frecruitment%252Fspecifications%252Fv1_0%252F%257DActiveLaborRecruitmentApplicationInfogetActiveApplicationByEstIdResponse/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:io="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0/"
    xmlns:io3="urn:kahramaa.com.qa/billing/xml/schemas/v1_0/"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io11="urn:igov.gov.qa/commonTypes/xml/schemas/v1_0/"
    xmlns:io2="urn:mol.gov.qa/customerService/recruitment/xml/schemas/v1_0/"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io6="urn:moi.gov.qa/establishmentInfo/xml/schemas/v1_0/"
    xmlns:io7="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io8="wsdl.urn:mol.gov.qa/customerService/recruitment/specifications/v1_0/"
    xmlns:io9="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io10="http://www.w3.org/2005/08/addressing"
    exclude-result-prefixes="xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="XSLTransformation1_req_13"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="XSLTransformation1_req_13">
    <body>
      <io:ActiveLaborRecruitmentApplicationInfogetActiveApplicationByEstIdResponse1>
        <io:application>
          <io2:Id>
            <!-- a simple mapping with no associated source:  to "io2:ApplicationNumber"(string) -->
            <io2:ApplicationNumber>
              <xsl:text>21321312</xsl:text>
            </io2:ApplicationNumber>
            <!-- a simple mapping with no associated source:  to "io2:year"(string) -->
            <io2:year>
              <xsl:text>2010</xsl:text>
            </io2:year>
          </io2:Id>
          <io2:details>
            <!-- a simple mapping with no associated source:  to "io2:establishmentName"(string) -->
            <io2:establishmentName>
              <xsl:text>المانع</xsl:text>
            </io2:establishmentName>
            <io2:requiredProfessions>
              <!-- a simple mapping with no associated source:  to "io2:requiredNumber"(int) -->
              <io2:requiredNumber>
                <xsl:text>5</xsl:text>
              </io2:requiredNumber>
              <io2:profession>
                <!-- a simple mapping with no associated source:  to "io11:name_En"(string) -->
                <io11:name_En>
                  <xsl:text>Engineer</xsl:text>
                </io11:name_En>
                <!-- a simple mapping with no associated source:  to "io11:name_Ar"(string) -->
                <io11:name_Ar>
                  <xsl:text>Mohandes</xsl:text>
                </io11:name_Ar>
                <!-- a simple mapping with no associated source:  to "io11:ID"(IdType) -->
                <io11:ID>
                  <xsl:text>1</xsl:text>
                </io11:ID>
              </io2:profession>
              <io2:nationality>
                <!-- a simple mapping with no associated source:  to "io11:name_En"(string) -->
                <io11:name_En>
                  <xsl:text>Egyption</xsl:text>
                </io11:name_En>
                <!-- a simple mapping with no associated source:  to "io11:name_Ar"(string) -->
                <io11:name_Ar>
                  <xsl:text>Masri</xsl:text>
                </io11:name_Ar>
                <!-- a simple mapping with no associated source:  to "io11:ID"(IdType) -->
                <io11:ID>
                  <xsl:text>1</xsl:text>
                </io11:ID>
              </io2:nationality>
              <!-- a simple mapping with no associated source:  to "io2:gender"(GenderType) -->
              <io2:gender>
                <xsl:text>MALE</xsl:text>
              </io2:gender>
              <!-- a simple mapping with no associated source:  to "io2:vpNumber"(string) -->
              <io2:vpNumber>
                <xsl:text>5</xsl:text>
              </io2:vpNumber>
            </io2:requiredProfessions>
            <io2:status>
              <!-- a simple mapping with no associated source:  to "io2:ID"(string) -->
              <io2:ID>
                <xsl:text>1</xsl:text>
              </io2:ID>
              <!-- a simple mapping with no associated source:  to "io2:nameEn"(string) -->
              <io2:nameEn>
                <xsl:text>under CSR review</xsl:text>
              </io2:nameEn>
            </io2:status>
            <!-- a simple mapping with no associated source:  to "io2:electricityNumber"(ElectricityNumberType) -->
            <io2:electricityNumber>
              <xsl:text>23212</xsl:text>
            </io2:electricityNumber>
            <!-- a simple mapping with no associated source:  to "io2:agentQID"(QIdType) -->
            <io2:agentQID>
              <xsl:text>21321321</xsl:text>
            </io2:agentQID>
            <!-- a simple mapping with no associated source:  to "io2:agentEmail"(EmailAddressType) -->
            <io2:agentEmail>
              <xsl:text>agent@hotmail.com</xsl:text>
            </io2:agentEmail>
            <!-- a simple mapping with no associated source:  to "io2:agentPhone"(TelephoneNumberType) -->
            <io2:agentPhone>
              <xsl:text>231221</xsl:text>
            </io2:agentPhone>
            <!-- a simple data mapping: "io:ActiveLaborRecruitmentApplicationInfogetActiveApplicationByEstIdRequest1/io:estID"(EstablishmentIdType) to "io2:establishmentID"(EstablishmentIdType) -->
            <io2:establishmentID>
              <xsl:value-of select="io:ActiveLaborRecruitmentApplicationInfogetActiveApplicationByEstIdRequest1/io:estID"/>
            </io2:establishmentID>
            <io2:establishmentAddress>
              <!-- a simple mapping with no associated source:  to "io11:poBox"(POBoxType) -->
              <io11:poBox>
                <xsl:text>9733</xsl:text>
              </io11:poBox>
            </io2:establishmentAddress>
          </io2:details>
        </io:application>
      </io:ActiveLaborRecruitmentApplicationInfogetActiveApplicationByEstIdResponse1>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
