<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_5.map" md5sum="60c37a6a14c50e11430ec7130a3520f2" version="6.2.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V6.2.200
*
*   Mapping file:		XSLTransformation1_req_5.map
*   Map declaration(s):	XSLTransformation1_req_5
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amoi.gov.qa%252FestablishmentInfo%252Fspecifications%252Fv1_0%252F%257DEstablishmentSecurityInfoisRestrictedRequest/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amoi.gov.qa%252FestablishmentInfo%252Fspecifications%252Fv1_0%252F%257DEstablishmentSecurityInfoisRestrictedResponse/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:io3="wsdl.urn:moi.gov.qa/establishmentInfo/specifications/v1_0/"
    xmlns:io2="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="urn:moi.gov.qa/establishmentInfo/xml/schemas/v1_0/"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="urn:moi.gov.qa/establishmentInfo/specifications/v1_0/"
    xmlns:io7="http://www.w3.org/2005/08/addressing"
    xmlns:io9="urn:igov.gov.qa/commonTypes/xml/schemas/v1_0/"
    xmlns:io10="urn:igov.gov.qa/xml/schemas/v1_0/"
    exclude-result-prefixes="xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="io:smo" mode="XSLTransformation1_req_5"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "io:smo" to "io:smo".  -->
  <xsl:template match="io:smo"  mode="XSLTransformation1_req_5">
    <io:smo>
      <body>
        <io8:EstablishmentSecurityInfoisRestrictedResponse1>
          <!-- a simple mapping with no associated source:  to "io8:restricted"(RestrictedEstablishment) -->
          <io8:restricted>
            <xsl:text>false</xsl:text>
          </io8:restricted>
        </io8:EstablishmentSecurityInfoisRestrictedResponse1>
      </body>
    </io:smo>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
