<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_9.map" md5sum="42158456a253162633ef05a73c2b25f3" version="6.2.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V6.2.200
*
*   Mapping file:		XSLTransformation1_req_9.map
*   Map declaration(s):	XSLTransformation1_req_9
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Akahramaa.com.qa%252Fbilling%252Fspecifications%252Fv1_0%252F%257DBillInfogetLastBillSummaryRequest/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Akahramaa.com.qa%252Fbilling%252Fspecifications%252Fv1_0%252F%257DBillInfogetLastBillSummaryResponse/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:io2="urn:kahramaa.com.qa/billing/xml/schemas/v1_0/"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io10="urn:igov.gov.qa/commonTypes/xml/schemas/v1_0/"
    xmlns:io11="urn:igov.gov.qa/xml/schemas/v1_0/"
    xmlns:io="urn:kahramaa.com.qa/billing/specifications/v1_0/"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io5="urn:moi.gov.qa/establishmentInfo/xml/schemas/v1_0/"
    xmlns:io6="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io8="wsdl.urn:kahramaa.com.qa/billing/specifications/v1_0/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io9="http://www.w3.org/2005/08/addressing"
    exclude-result-prefixes="xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="io3:smo" mode="XSLTransformation1_req_9"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "io3:smo" to "io3:smo".  -->
  <xsl:template match="io3:smo"  mode="XSLTransformation1_req_9">
    <io3:smo>
      <body>
        <io:BillInfogetLastBillSummaryResponse1>
          <io:billSummary>
            <!-- a simple mapping with no associated source:  to "io2:waterNumber"(string) -->
            <io2:waterNumber>
              <xsl:text>232231</xsl:text>
            </io2:waterNumber>
            <!-- a simple data mapping: "body/io:BillInfogetLastBillSummaryRequest1/io:elecNumber"(ElectricityNumberType) to "io2:electricityNumber"(ElectricityNumberType) -->
            <io2:electricityNumber>
              <xsl:value-of select="body/io:BillInfogetLastBillSummaryRequest1/io:elecNumber"/>
            </io2:electricityNumber>
            <!-- a simple mapping with no associated source:  to "io2:billNumber"(string) -->
            <io2:billNumber>
              <xsl:text>23212</xsl:text>
            </io2:billNumber>
            <!-- a simple mapping with no associated source:  to "io2:customerNameArabic"(string) -->
            <io2:customerNameArabic>
              <xsl:text>عبد الرحمن</xsl:text>
            </io2:customerNameArabic>
            <!-- a simple mapping with no associated source:  to "io2:accountId"(string) -->
            <io2:accountId>
              <xsl:text>22132</xsl:text>
            </io2:accountId>
            <!-- a simple mapping with no associated source:  to "io2:lastPaidDate"(dateTime) -->
            <io2:lastPaidDate>
              <xsl:text>2010-05-30T09:00:00</xsl:text>
            </io2:lastPaidDate>
            <!-- a simple mapping with no associated source:  to "io2:outstandingAmount"(string) -->
            <io2:outstandingAmount>
              <xsl:text>21321213</xsl:text>
            </io2:outstandingAmount>
          </io:billSummary>
        </io:BillInfogetLastBillSummaryResponse1>
      </body>
    </io3:smo>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
