<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="EstablishmentRestrictionInfoService" targetNamespace="http://moi.gov.qa/establishmentInfo/services/v1_0/EstablishmentRestrictionInfoService/" xmlns:moispcxsd="urn:moi.gov.qa/establishmentInfo/specifications/v1_0/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://moi.gov.qa/establishmentInfo/services/v1_0/EstablishmentRestrictionInfoService/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="../../specifications/v1_0/EstablishmentRestrictionInfo_v1_0.wsdl" namespace="urn:moi.gov.qa/establishmentInfo/specifications/v1_0/"/>
  <wsdl:binding name="EstablishmentRestrictionInfoBinding" type="moispcxsd:EstablishmentRestrictionInfo">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="isRestricted">
      <soap:operation soapAction="http://moi.gov.qa/establishmentInfo/services/v1_0/EstablishmentRestrictionInfoService/isRestricted/"/>
      <wsdl:input>
        <soap:body parts="estID" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="restricted" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="isRestrictedFault">
        <soap:fault name="isRestrictedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="establishmentRestrictionInfo">
    <wsdl:port binding="tns:EstablishmentRestrictionInfoBinding" name="EstablishmentRestrictionInfoPort">
      <soap:address location="http://moi.gov.qa/establishmentInfo/services/v1_0/EstablishmentRestrictionInfoService/establishmentRestrictionInfo/EstablishmentRestrictionInfoPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>