<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="swimlane2" targetNamespace="http://LR_SiwmLane2/qa/gov/ict/process/swimlane2/swimlane2Artifacts" xmlns:ns="http://mol.gov.qa/Process/WSDL/ISwimLane2/v1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plnk:partnerLinkType name="ISwimLane2PLT">
    <plnk:role name="Interface">
      <plnk:portType name="ns:IDepartmentStudy"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <wsdl:import location="../../../../../process/IDepartmentStudy.wsdl" namespace="http://mol.gov.qa/Process/WSDL/ISwimLane2/v1"/>
</wsdl:definitions>