<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_5.map" md5sum="644b71a3869ce03c8c9018eaf2c46a2c" version="6.2.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V6.2.200
*
*   Mapping file:		XSLTransformation1_req_5.map
*   Map declaration(s):	XSLTransformation1_req_5
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amec.gov.qa%252FcommercialRegistration%252Fspecifications%252Fv1_0%252F%257DCommercialRegistrationInfogetCommercialRegistrationInfoRequest/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amec.gov.qa%252FcommercialRegistration%252Fspecifications%252Fv1_0%252F%257DCommercialRegistrationInfogetCommercialRegistrationInfoResponse/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:io="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="wsdl.urn:mec.gov.qa/commercialRegistration/specifications/v1_0/"
    xmlns:io10="urn:igov.gov.qa/commonTypes/xml/schemas/v1_0/"
    xmlns:io11="urn:igov.gov.qa/xml/schemas/v1_0/"
    xmlns:io2="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io3="urn:mec.gov.qa/commercialRegistration/xml/schemas/v1_0/"
    xmlns:io4="urn:moi.gov.qa/establishmentInfo/xml/schemas/v1_0/"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="urn:mec.gov.qa/commercialRegistration/specifications/v1_0/"
    xmlns:io9="http://www.w3.org/2005/08/addressing"
    exclude-result-prefixes="xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="XSLTransformation1_req_5"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="XSLTransformation1_req_5">
    <body>
      <io8:CommercialRegistrationInfogetCommercialRegistrationInfoResponse1>
        <io8:commercialRegistration>
          <!-- a simple mapping with no associated source:  to "io3:location"(string) -->
          <io3:location>
            <xsl:text>الدوحه</xsl:text>
          </io3:location>
          <!-- a simple mapping with no associated source:  to "io3:creationDate"(dateTime) -->
          <io3:creationDate>
            <xsl:text>2001-10-26T21:32:52</xsl:text>
          </io3:creationDate>
          <!-- a simple mapping with no associated source:  to "io3:arabicCommercialName"(string) -->
          <io3:arabicCommercialName>
            <xsl:text>العمادى</xsl:text>
          </io3:arabicCommercialName>
          <!-- a simple mapping with no associated source:  to "io3:companyCapital"(double) -->
          <io3:companyCapital>
            <xsl:text>20</xsl:text>
          </io3:companyCapital>
        </io8:commercialRegistration>
      </io8:CommercialRegistrationInfogetCommercialRegistrationInfoResponse1>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
