<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_4.map" md5sum="ac634aa471555caaaec568dc3deb6237" version="6.2.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V6.2.200
*
*   Mapping file:		XSLTransformation1_req_4.map
*   Map declaration(s):	XSLTransformation1_req_4
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Abaladiya.gov.qa%252FcommercialPermit%252Fspecifications%252Fv1_0%252F%257DCommercialPermitInfogetCommercialPermitInfoRequest/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Abaladiya.gov.qa%252FcommercialPermit%252Fspecifications%252Fv1_0%252F%257DCommercialPermitInfogetCommercialPermitInfoResponse/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io8="wsdl.urn:baladiya.gov.qa/commercialPermit/specifications/v1_0/"
    xmlns:io10="urn:igov.gov.qa/commonTypes/xml/schemas/v1_0/"
    xmlns:io="urn:baladiya.gov.qa/commonTypes/xml/schemas/v1_0/"
    xmlns:io2="urn:baladiya.gov.qa/commercialPermit/specifications/v1_0/"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io5="urn:moi.gov.qa/establishmentInfo/xml/schemas/v1_0/"
    xmlns:io6="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io9="http://www.w3.org/2005/08/addressing"
    xmlns:io11="urn:baladiya.gov.qa/commercialPermit/xml/schemas/v1_0/"
    exclude-result-prefixes="xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="XSLTransformation1_req_4"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="XSLTransformation1_req_4">
    <body>
      <io2:CommercialPermitInfogetCommercialPermitInfoResponse1>
        <io2:commercialPermit>
          <io11:commercialRegistration>
            <!-- a simple mapping with no associated source:  to "io11:ID"(string) -->
            <io11:ID>
              <xsl:text>232223</xsl:text>
            </io11:ID>
            <!-- a simple mapping with no associated source:  to "io11:branchNumber"(string) -->
            <io11:branchNumber>
              <xsl:text>0</xsl:text>
            </io11:branchNumber>
          </io11:commercialRegistration>
          <io11:establishmentCommercialName>
            <!-- a simple mapping with no associated source:  to "io:nameArabic"(string) -->
            <io:nameArabic>
              <xsl:text>المعادى</xsl:text>
            </io:nameArabic>
          </io11:establishmentCommercialName>
          <!-- a simple mapping with no associated source:  to "io11:issueDate"(dateTime) -->
          <io11:issueDate>
            <xsl:text>2008-10-26T21:32:52</xsl:text>
          </io11:issueDate>
          <!-- a simple mapping with no associated source:  to "io11:expiryDate"(dateTime) -->
          <io11:expiryDate>
            <xsl:text>2011-10-26T21:32:52</xsl:text>
          </io11:expiryDate>
          <!-- a simple mapping with no associated source:  to "io11:commercialPermitID"(CommercialPermitIDType) -->
          <io11:commercialPermitID>
            <xsl:text>12</xsl:text>
          </io11:commercialPermitID>
          <io11:applicationNumber>
            <!-- a simple mapping with no associated source:  to "io11:municipalityID"(string) -->
            <io11:municipalityID>
              <xsl:text>4324</xsl:text>
            </io11:municipalityID>
            <!-- a simple mapping with no associated source:  to "io11:year"(string) -->
            <io11:year>
              <xsl:text>2010</xsl:text>
            </io11:year>
            <!-- a simple mapping with no associated source:  to "io11:number"(string) -->
            <io11:number>
              <xsl:text>15</xsl:text>
            </io11:number>
          </io11:applicationNumber>
        </io2:commercialPermit>
      </io2:CommercialPermitInfogetCommercialPermitInfoResponse1>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
