<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_3.map" md5sum="224d277998ea8fac0cfeaad6db84a725" version="6.2.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V6.2.200
*
*   Mapping file:		XSLTransformation1_req_3.map
*   Map declaration(s):	XSLTransformation1_req_3
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amoi.gov.qa%252FestablishmentInfo%252Fspecifications%252Fv1_0%252F%257DEstablishmentLaborStatisticsInfogetLaborStatisticsRequest/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amoi.gov.qa%252FestablishmentInfo%252Fspecifications%252Fv1_0%252F%257DEstablishmentLaborStatisticsInfogetLaborStatisticsResponse/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io="wsdl.urn:moi.gov.qa/establishmentInfo/specifications/v1_0/"
    xmlns:io4="urn:moi.gov.qa/establishmentInfo/xml/schemas/v1_0/"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:io7="urn:moi.gov.qa/establishmentInfo/specifications/v1_0/"
    xmlns:io9="urn:igov.gov.qa/commonTypes/xml/schemas/v1_0/"
    exclude-result-prefixes="xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="yes" xalan:indent-amount="2"/>
  <xsl:strip-space elements="*"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="XSLTransformation1_req_3"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="XSLTransformation1_req_3">
    <body>
      <io7:EstablishmentLaborStatisticsInfogetLaborStatisticsResponse1>
        <io7:estStatistics>
          <io4:professions>
            <!-- a simple mapping with no associated source:  to "io4:permittedVisaCount"(int) -->
            <io4:permittedVisaCount>
              <xsl:text>12</xsl:text>
            </io4:permittedVisaCount>
            <!-- a simple mapping with no associated source:  to "io4:usedVisaCount"(int) -->
            <io4:usedVisaCount>
              <xsl:text>2</xsl:text>
            </io4:usedVisaCount>
            <!-- a simple mapping with no associated source:  to "io4:remainingVisaCount"(int) -->
            <io4:remainingVisaCount>
              <xsl:text>10</xsl:text>
            </io4:remainingVisaCount>
            <io4:profession>
              <!-- a simple mapping with no associated source:  to "io9:name_Ar"(string) -->
              <io9:name_Ar>
                <xsl:text>Engineer</xsl:text>
              </io9:name_Ar>
              <!-- a simple mapping with no associated source:  to "io9:ID"(IdType) -->
              <io9:ID>
                <xsl:text>123</xsl:text>
              </io9:ID>
            </io4:profession>
            <io4:nationality>
              <!-- a simple mapping with no associated source:  to "io9:name_Ar"(string) -->
              <io9:name_Ar>
                <xsl:text>Egpyrion</xsl:text>
              </io9:name_Ar>
              <!-- a simple mapping with no associated source:  to "io9:ID"(IdType) -->
              <io9:ID>
                <xsl:text>444</xsl:text>
              </io9:ID>
            </io4:nationality>
            <!-- a simple mapping with no associated source:  to "io4:gender"(GenderType) -->
            <io4:gender>
              <xsl:text>Male</xsl:text>
            </io4:gender>
            <!-- a simple mapping with no associated source:  to "io4:vpNumber"(string) -->
            <io4:vpNumber>
              <xsl:text>34343232</xsl:text>
            </io4:vpNumber>
          </io4:professions>
        </io7:estStatistics>
      </io7:EstablishmentLaborStatisticsInfogetLaborStatisticsResponse1>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
