<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="LaborRecruitmentBusinessRulesService" targetNamespace="http://mol.gov.qa/customerService/recruitment/services/v1_0/LaborRecruitmentBusinessRulesService/" xmlns:molspcxsd="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://mol.gov.qa/customerService/recruitment/services/v1_0/LaborRecruitmentBusinessRulesService/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="../../specifications/v1_0/LaborRecruitmentBusinessRules_v1_0.wsdl" namespace="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0/"/>
  <wsdl:binding name="LaborRecruitmentBusinessRulesBinding" type="molspcxsd:LaborRecruitmentBusinessRules">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="checkEstablishment">
      <soap:operation soapAction="http://mol.gov.qa/customerService/recruitment/services/v1_0/LaborRecruitmentBusinessRulesService/checkEstablishment/"/>
      <wsdl:input>
        <soap:body parts="estID" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="validEstblishment" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="checkEstablishmentFault">
        <soap:fault name="checkEstablishmentFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="laborRecruitmentBusinessRules">
    <wsdl:port binding="tns:LaborRecruitmentBusinessRulesBinding" name="LaborRecruitmentBusinessRulesPort">
      <soap:address location="http://mol.gov.qa/customerService/recruitment/services/v1_0/LaborRecruitmentBusinessRulesService/laborRecruitmentBusinessRules/LaborRecruitmentBusinessRulesPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>