<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="RecruitmentProcessResumeApplicationExport1_RecruitmentProcessResumeApplicationHttp_Service" targetNamespace="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0//Binding3" xmlns:Port_0="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0//Binding3" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="RecruitmentProcessResumeApplication_v1_0.wsdl" namespace="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0/"/>
  <wsdl:binding name="RecruitmentProcessResumeApplicationExport1_RecruitmentProcessResumeApplicationHttpBinding" type="Port_0:RecruitmentProcessResumeApplication">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="resumeApplication">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="resumeApplicationFault">
        <soap:fault name="resumeApplicationFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RecruitmentProcessResumeApplicationExport1_RecruitmentProcessResumeApplicationHttpService">
    <wsdl:port binding="this:RecruitmentProcessResumeApplicationExport1_RecruitmentProcessResumeApplicationHttpBinding" name="RecruitmentProcessResumeApplicationExport1_RecruitmentProcessResumeApplicationHttpPort">
      <soap:address location="http://localhost:9080/mol_recruit_reviewapplication_processWeb/sca/RecruitmentProcessResumeApplicationExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>