<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="BlacklistedEstablishmentsInfoExport1_BlacklistedEstablishmentsInfoHttp_Service" targetNamespace="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0//Binding7" xmlns:Port_0="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0//Binding7" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="mol/gov/qa/customerService/recruitment/specifications/v1_0/BlacklistedEstablishmentInfo_v1_0.wsdl" namespace="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0/"/>
  <wsdl:binding name="BlacklistedEstablishmentsInfoExport1_BlacklistedEstablishmentsInfoHttpBinding" type="Port_0:BlacklistedEstablishmentsInfo">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="isEstablishmentBlacklisted">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="isEstablishmentBlacklistedFault">
        <soap:fault name="isEstablishmentBlacklistedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BlacklistedEstablishmentsInfoExport1_BlacklistedEstablishmentsInfoHttpService">
    <wsdl:port binding="this:BlacklistedEstablishmentsInfoExport1_BlacklistedEstablishmentsInfoHttpBinding" name="BlacklistedEstablishmentsInfoExport1_BlacklistedEstablishmentsInfoHttpPort">
      <soap:address location="http://localhost:9080/gsb_servicesStubsWeb/sca/BlacklistedEstablishmentsInfoExport1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>