<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="RecruitmentProcessResumeApplicationService" targetNamespace="http://mol.gov.qa/customerService/recruitment/services/v1_0/RecruitmentProcessResumeApplicationService/" xmlns:molspcxsd="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://mol.gov.qa/customerService/recruitment/services/v1_0/RecruitmentProcessResumeApplicationService/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="../../specifications/v1_0/RecruitmentProcessResumeApplication_v1_0.wsdl" namespace="urn:mol.gov.qa/customerService/recruitment/specifications/v1_0/"/>
  <wsdl:binding name="RecruitmentProcessResumeApplicationBinding" type="molspcxsd:RecruitmentProcessResumeApplication">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="resumeApplication">
      <soap:operation soapAction="http://mol.gov.qa/customerService/recruitment/services/v1_0/RecruitmentProcessResumeApplicationService/resumeApplication/"/>
      <wsdl:input>
        <soap:body parts="resumeApplicationRequest" use="literal"/>
        <soap:header part="processHeader" message="molspcxsd:RecruitmentProcessResumeApplicationresumeApplicationRequest" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body parts="resumeApplicationResponse" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="resumeApplicationFault">
        <soap:fault name="resumeApplicationFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="recruitmentProcessResumeApplication">
    <wsdl:port binding="tns:RecruitmentProcessResumeApplicationBinding" name="RecruitmentProcessResumeApplicationPort">
      <soap:address location="http://mol.gov.qa/customerService/recruitment/services/v1_0/RecruitmentProcessResumeApplicationService/recruitmentProcessResumeApplication/RecruitmentProcessResumeApplicationPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>