--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "SOA_ RCT_ RQS_PROF" DROP CONSTRAINT "REQUIRED_PROFESSI_NATIONALI_FK";

ALTER TABLE "SOA_ RCT_ RQS_PROF" DROP CONSTRAINT "REQUIRED_PROFESSI_PROFESSI_FK";

ALTER TABLE "SOA_ RCT_ RQS_PROF" DROP CONSTRAINT "Required Profes_Application_FK";

ALTER TABLE "SOA_ RCT_APV_ PROF" DROP CONSTRAINT "APPROVED_PROFESSI_NATIONALI_FK";

ALTER TABLE "SOA_ RCT_APV_ PROF" DROP CONSTRAINT "APPROVED_PROFESSI_PROFESSI_FK";

ALTER TABLE "SOA_ RCT_APV_ PROF" DROP CONSTRAINT "APPROVED_PROFE_APPLICATION_FK";

ALTER TABLE "SOA_ RCT_CSR_REV" DROP CONSTRAINT "Review Resu_Application Vi_FK";

ALTER TABLE "SOA_LBR_EST_DTL" DROP CONSTRAINT "SOA_LBR_EST_DTL_SOA_LBR_EST_FK";

ALTER TABLE "SOA_LBR_EST_PERSON" DROP CONSTRAINT "SOA_LBR_EST_PERS_SOA_LBR_E_FK";

ALTER TABLE "SOA_LBR_EST_PERSON" DROP CONSTRAINT "SOA_LBR_ES_SOA_LBR_EST_PER_FK";

ALTER TABLE "SOA_LBR_EST_PERSON_INFO" DROP CONSTRAINT "SOA_LBR_EST_PERSON_SOA_LBR_FK";

ALTER TABLE "SOA_LBR_EST_PROF_STATISTICS" DROP CONSTRAINT "SOA_LBR_EST_PROF_STAT_SOA_L_FK";

ALTER TABLE "SOA_LBR_EST_PROF_STATISTICS" DROP CONSTRAINT "SOA_LBR_EST_PROF_STA_SOA_L_FK";

ALTER TABLE "SOA_LBR_EST_PROF_STATISTICS" DROP CONSTRAINT "SOA_LBR_EST_PROF_STA_SOA_L_FK1";

ALTER TABLE "SOA_LBR_RCT_APP" DROP CONSTRAINT "SOA_LBR_RCT_APP_SOA_LBR_EST_FK";

ALTER TABLE "SOA_LBR_RCT_APP" DROP CONSTRAINT "SOA_LBR_RCT_SOA_LBR_RCT_ST_FK";

ALTER TABLE "SOA_LBR_RCT_APP" DROP CONSTRAINT "SOA_LBR_RCT__SOA_LBR_RCT_F_FK";

ALTER TABLE "SOA_ RCT_ RQS_PROF" DROP CONSTRAINT "REQUIRED_PROFESSION_PK";

ALTER TABLE "SOA_ RCT_APV_ PROF" DROP CONSTRAINT "APPROVED_PROFESSION_PK";

ALTER TABLE "SOA_ RCT_CSR_REV" DROP CONSTRAINT "REVIEW_RESULT_PK";

ALTER TABLE "SOA_LBR_ NAT" DROP CONSTRAINT "Nationality_PK";

ALTER TABLE "SOA_LBR_EST" DROP CONSTRAINT "SOA_LBR_EST_PK";

ALTER TABLE "SOA_LBR_EST_DTL" DROP CONSTRAINT "SOA_LBR_EST_DTL_PK";

ALTER TABLE "SOA_LBR_EST_PERSON" DROP CONSTRAINT "SOA_LBR_EST_PERSON_PK";

ALTER TABLE "SOA_LBR_EST_PERSON_INFO" DROP CONSTRAINT "SOA_LBR_EST_PERSON_INFO_PK";

ALTER TABLE "SOA_LBR_EST_PROF_STATISTICS" DROP CONSTRAINT "SOA_LBR_EST_PROF_STATISTICS_PK";

ALTER TABLE "SOA_LBR_PROF" DROP CONSTRAINT "Professions_PK";

ALTER TABLE "SOA_LBR_RCT_APP" DROP CONSTRAINT "Application View_PK";

ALTER TABLE "SOA_LBR_RCT_FEES" DROP CONSTRAINT "SOA_LBR_RCT_FEES_PK";

ALTER TABLE "SOA_LBR_RCT_STATUS" DROP CONSTRAINT "SOA_LBR_RCT_STATUS_PK";

DROP TABLE "SOA_ RCT_ RQS_PROF";

DROP TABLE "SOA_ RCT_APV_ PROF";

DROP TABLE "SOA_ RCT_CSR_REV";

DROP TABLE "SOA_LBR_ NAT";

DROP TABLE "SOA_LBR_EST";

DROP TABLE "SOA_LBR_EST_DTL";

DROP TABLE "SOA_LBR_EST_PERSON";

DROP TABLE "SOA_LBR_EST_PERSON_INFO";

DROP TABLE "SOA_LBR_EST_PROF_STATISTICS";

DROP TABLE "SOA_LBR_PROF";

DROP TABLE "SOA_LBR_RCT_APP";

DROP TABLE "SOA_LBR_RCT_FEES";

DROP TABLE "SOA_LBR_RCT_STATUS";

CREATE TABLE "SOA_ RCT_ RQS_PROF" (
		"GENDER" NUMBER(1 , 0) NOT NULL,
		"REQUIRED_COUNT" NUMBER(4 , 0) NOT NULL,
		"PROFESSION_ID" NUMBER(4 , 0) NOT NULL,
		"NATIONALITY_ID" NUMBER(3 , 0) NOT NULL,
		"APPLICATION_NO" VARCHAR2(8) NOT NULL,
		"YEAR" VARCHAR2(4) NOT NULL
	)
	LOGGING;

CREATE TABLE "SOA_ RCT_APV_ PROF" (
		"GENDER" NUMBER(1 , 0) NOT NULL,
		"APPROVED_COUNT" NUMBER(4 , 0) NOT NULL,
		"APPLICATION_NO" VARCHAR2(8) NOT NULL,
		"YEAR" VARCHAR2(4) NOT NULL,
		"PROFESSION_ID" NUMBER(4 , 0) NOT NULL,
		"NATIONALITY_ID" NUMBER(3 , 0) NOT NULL,
		"VP_NUMBER" VARCHAR2(12)
	)
	LOGGING;

CREATE TABLE "SOA_ RCT_CSR_REV" (
		"RESULT" NUMBER(1 , 0) NOT NULL,
		"USER_ID" VARCHAR2(30) NOT NULL,
		"REVIEW_DATE" DATE NOT NULL,
		"REMARK" VARCHAR2(2000),
		"NOTIFICATION" VARCHAR2(450),
		"APPLICATION_NO" VARCHAR2(8) NOT NULL,
		"YEAR" VARCHAR2(4) NOT NULL,
		"NOTIFICATION_LANG" NUMBER(1 , 0)
	)
	LOGGING;

CREATE TABLE "SOA_LBR_ NAT" (
		"NATIONALITY_ID" NUMBER(3 , 0) NOT NULL,
		"NAME_AR" VARCHAR2(100) NOT NULL,
		"NAME_EN" VARCHAR2(100)
	)
	LOGGING;

CREATE TABLE "SOA_LBR_EST" (
		"EST_ID" VARCHAR2(8) NOT NULL,
		"EST_NAME" VARCHAR2(1000) NOT NULL,
		"EMAIL" VARCHAR2(256),
		"CURRENT_WORKERS_COUNT" NUMBER(9 , 0)
	)
	LOGGING;

CREATE TABLE "SOA_LBR_EST_DTL" (
		"PHONE_NUMBER" VARCHAR2(25),
		"ADDRESS_STREET_NUMBER" VARCHAR2(20),
		"ADDRESS_BUILDING_NUMBER" VARCHAR2(20),
		"EST_ID" VARCHAR2(8) NOT NULL,
		"ADDRESS_ZONE" VARCHAR2(20),
		"ADDRESS_TEXT" VARCHAR2(2000)
	)
	LOGGING;

CREATE TABLE "SOA_LBR_EST_PERSON" (
		"EST_ID" VARCHAR2(8) NOT NULL,
		"QID" VARCHAR2(11) NOT NULL,
		"DESIGNATION" NUMBER(1 , 0) NOT NULL
	)
	LOGGING;

CREATE TABLE "SOA_LBR_EST_PERSON_INFO" (
		"QID" VARCHAR2(11) NOT NULL,
		"NAME_AR" VARCHAR2(1000) NOT NULL,
		"NAME_EN" VARCHAR2(1000),
		"BUSINESS_PHONE" VARCHAR2(25),
		"NATIONALITY_ID" NUMBER(3 , 0)
	)
	LOGGING;

CREATE TABLE "SOA_LBR_EST_PROF_STATISTICS" (
		"VISA_PERMITTED_COUNT" NUMBER(9 , 0),
		"VISA_USED_COUNT" NUMBER(9 , 0),
		"VISA_REMAIN_COUNT" NUMBER(9 , 0),
		"PROFESSION_ID" NUMBER(4 , 0) NOT NULL,
		"NATIONALITY_ID" NUMBER(3 , 0) NOT NULL,
		"EST_ID" VARCHAR2(8) NOT NULL,
		"GENDER" NUMBER(1 , 0) NOT NULL,
		"VP_NUMBER" VARCHAR2(12) NOT NULL,
		"APPLICATION_NUMBER" VARCHAR2(8),
		"YEAR" VARCHAR2(4),
		"EXPIRY_DATE" DATE
	)
	LOGGING;

CREATE TABLE "SOA_LBR_PROF" (
		"PROFESSION_ID" NUMBER(4 , 0) NOT NULL,
		"NAME_AR" VARCHAR2(100) NOT NULL,
		"NAME_EN" VARCHAR2(100)
	)
	LOGGING;

CREATE TABLE "SOA_LBR_RCT_APP" (
		"APPLICATION_NO" VARCHAR2(8) NOT NULL,
		"YEAR" VARCHAR2(4) NOT NULL,
		"EST_ID" VARCHAR2(8) NOT NULL,
		"APPLICATION_DATE" DATE NOT NULL,
		"ELECTRICITY_NO" VARCHAR2(8),
		"AGENT_QID" VARCHAR2(11) NOT NULL,
		"AGENT_MOBILE" VARCHAR2(7),
		"AGENT_EMAIL" VARCHAR2(256),
		"STATUS_ID" NUMBER(3 , 0) NOT NULL,
		"REMARKS" VARCHAR2(2000),
		"ACTIVE_APP" NUMBER(1 , 0) NOT NULL,
		"PAYMENT_TRANSACTION_ID" VARCHAR2(100),
		"PAYMENT_STATUS" VARCHAR2(5),
		"PAYMENT_DATE" DATE,
		"PAYMENT_AMOUNT" NUMBER(8 , 2),
		"PAYMENT_RECEIPT_NUMBER" VARCHAR2(100),
		"SERVICE_FEES_ID" VARCHAR2(10),
		"COMM_REGISTRATION_NO" VARCHAR2(20),
		"COMM_PERMIT_NO" VARCHAR2(200)
	)
	LOGGING;

CREATE TABLE "SOA_LBR_RCT_FEES" (
		"SERVICE_FEES_ID" VARCHAR2(10) NOT NULL,
		"SERVICE_FEES_AMOUNT" NUMBER(8 , 2) NOT NULL,
		"SERVICE_FEES_DESCRIPTION" VARCHAR2(2000)
	)
	LOGGING;

CREATE TABLE "SOA_LBR_RCT_STATUS" (
		"STATUS_ID" NUMBER(3 , 0) NOT NULL,
		"STATUS_AR" VARCHAR2(100) NOT NULL,
		"STATUS_EN" VARCHAR2(100)
	)
	LOGGING;

ALTER TABLE "SOA_ RCT_ RQS_PROF" ADD CONSTRAINT "REQUIRED_PROFESSION_PK" PRIMARY KEY
	("PROFESSION_ID",
	 "NATIONALITY_ID",
	 "APPLICATION_NO",
	 "YEAR",
	 "GENDER");

ALTER TABLE "SOA_ RCT_APV_ PROF" ADD CONSTRAINT "APPROVED_PROFESSION_PK" PRIMARY KEY
	("APPLICATION_NO",
	 "YEAR",
	 "PROFESSION_ID",
	 "NATIONALITY_ID",
	 "GENDER");

ALTER TABLE "SOA_LBR_ NAT" ADD CONSTRAINT "Nationality_PK" PRIMARY KEY
	("NATIONALITY_ID");

ALTER TABLE "SOA_LBR_EST" ADD CONSTRAINT "SOA_LBR_EST_PK" PRIMARY KEY
	("EST_ID");

ALTER TABLE "SOA_LBR_EST_DTL" ADD CONSTRAINT "SOA_LBR_EST_DTL_PK" PRIMARY KEY
	("EST_ID");

ALTER TABLE "SOA_LBR_EST_PERSON" ADD CONSTRAINT "SOA_LBR_EST_PERSON_PK" PRIMARY KEY
	("EST_ID",
	 "QID",
	 "DESIGNATION");

ALTER TABLE "SOA_LBR_EST_PERSON_INFO" ADD CONSTRAINT "SOA_LBR_EST_PERSON_INFO_PK" PRIMARY KEY
	("QID");

ALTER TABLE "SOA_LBR_EST_PROF_STATISTICS" ADD CONSTRAINT "SOA_LBR_EST_PROF_STATISTICS_PK" PRIMARY KEY
	("PROFESSION_ID",
	 "NATIONALITY_ID",
	 "EST_ID",
	 "GENDER",
	 "VP_NUMBER");

ALTER TABLE "SOA_LBR_PROF" ADD CONSTRAINT "Professions_PK" PRIMARY KEY
	("PROFESSION_ID");

ALTER TABLE "SOA_LBR_RCT_APP" ADD CONSTRAINT "Application View_PK" PRIMARY KEY
	("APPLICATION_NO",
	 "YEAR");

ALTER TABLE "SOA_LBR_RCT_FEES" ADD CONSTRAINT "SOA_LBR_RCT_FEES_PK" PRIMARY KEY
	("SERVICE_FEES_ID");

ALTER TABLE "SOA_LBR_RCT_STATUS" ADD CONSTRAINT "SOA_LBR_RCT_STATUS_PK" PRIMARY KEY
	("STATUS_ID");

ALTER TABLE "SOA_ RCT_ RQS_PROF" ADD CONSTRAINT "REQUIRED_PROFESSI_NATIONALI_FK" FOREIGN KEY
	("NATIONALITY_ID")
	REFERENCES "SOA_LBR_ NAT"
	("NATIONALITY_ID")
	ON DELETE CASCADE;

ALTER TABLE "SOA_ RCT_ RQS_PROF" ADD CONSTRAINT "REQUIRED_PROFESSI_PROFESSI_FK" FOREIGN KEY
	("PROFESSION_ID")
	REFERENCES "SOA_LBR_PROF"
	("PROFESSION_ID")
	ON DELETE CASCADE;

ALTER TABLE "SOA_ RCT_ RQS_PROF" ADD CONSTRAINT "Required Profes_Application_FK" FOREIGN KEY
	("APPLICATION_NO",
	 "YEAR")
	REFERENCES "SOA_LBR_RCT_APP"
	("APPLICATION_NO",
	 "YEAR")
	ON DELETE RESTRICT;

ALTER TABLE "SOA_ RCT_APV_ PROF" ADD CONSTRAINT "APPROVED_PROFESSI_NATIONALI_FK" FOREIGN KEY
	("NATIONALITY_ID")
	REFERENCES "SOA_LBR_ NAT"
	("NATIONALITY_ID")
	ON DELETE CASCADE;

ALTER TABLE "SOA_ RCT_APV_ PROF" ADD CONSTRAINT "APPROVED_PROFESSI_PROFESSI_FK" FOREIGN KEY
	("PROFESSION_ID")
	REFERENCES "SOA_LBR_PROF"
	("PROFESSION_ID")
	ON DELETE CASCADE;

ALTER TABLE "SOA_ RCT_APV_ PROF" ADD CONSTRAINT "APPROVED_PROFE_APPLICATION_FK" FOREIGN KEY
	("APPLICATION_NO",
	 "YEAR")
	REFERENCES "SOA_LBR_RCT_APP"
	("APPLICATION_NO",
	 "YEAR");

ALTER TABLE "SOA_ RCT_CSR_REV" ADD CONSTRAINT "Review Resu_Application Vi_FK" FOREIGN KEY
	("APPLICATION_NO",
	 "YEAR")
	REFERENCES "SOA_LBR_RCT_APP"
	("APPLICATION_NO",
	 "YEAR")
	ON DELETE RESTRICT;

ALTER TABLE "SOA_LBR_EST_DTL" ADD CONSTRAINT "SOA_LBR_EST_DTL_SOA_LBR_EST_FK" FOREIGN KEY
	("EST_ID")
	REFERENCES "SOA_LBR_EST"
	("EST_ID")
	ON DELETE CASCADE;

ALTER TABLE "SOA_LBR_EST_PERSON" ADD CONSTRAINT "SOA_LBR_EST_PERS_SOA_LBR_E_FK" FOREIGN KEY
	("EST_ID")
	REFERENCES "SOA_LBR_EST"
	("EST_ID")
	ON DELETE CASCADE;

ALTER TABLE "SOA_LBR_EST_PERSON" ADD CONSTRAINT "SOA_LBR_ES_SOA_LBR_EST_PER_FK" FOREIGN KEY
	("QID")
	REFERENCES "SOA_LBR_EST_PERSON_INFO"
	("QID")
	ON DELETE CASCADE;

ALTER TABLE "SOA_LBR_EST_PERSON_INFO" ADD CONSTRAINT "SOA_LBR_EST_PERSON_SOA_LBR_FK" FOREIGN KEY
	("NATIONALITY_ID")
	REFERENCES "SOA_LBR_ NAT"
	("NATIONALITY_ID");

ALTER TABLE "SOA_LBR_EST_PROF_STATISTICS" ADD CONSTRAINT "SOA_LBR_EST_PROF_STAT_SOA_L_FK" FOREIGN KEY
	("EST_ID")
	REFERENCES "SOA_LBR_EST"
	("EST_ID")
	ON DELETE CASCADE;

ALTER TABLE "SOA_LBR_EST_PROF_STATISTICS" ADD CONSTRAINT "SOA_LBR_EST_PROF_STA_SOA_L_FK" FOREIGN KEY
	("PROFESSION_ID")
	REFERENCES "SOA_LBR_PROF"
	("PROFESSION_ID")
	ON DELETE CASCADE;

ALTER TABLE "SOA_LBR_EST_PROF_STATISTICS" ADD CONSTRAINT "SOA_LBR_EST_PROF_STA_SOA_L_FK1" FOREIGN KEY
	("NATIONALITY_ID")
	REFERENCES "SOA_LBR_ NAT"
	("NATIONALITY_ID")
	ON DELETE CASCADE;

ALTER TABLE "SOA_LBR_RCT_APP" ADD CONSTRAINT "SOA_LBR_RCT_APP_SOA_LBR_EST_FK" FOREIGN KEY
	("EST_ID")
	REFERENCES "SOA_LBR_EST"
	("EST_ID");

ALTER TABLE "SOA_LBR_RCT_APP" ADD CONSTRAINT "SOA_LBR_RCT_SOA_LBR_RCT_ST_FK" FOREIGN KEY
	("STATUS_ID")
	REFERENCES "SOA_LBR_RCT_STATUS"
	("STATUS_ID");

ALTER TABLE "SOA_LBR_RCT_APP" ADD CONSTRAINT "SOA_LBR_RCT__SOA_LBR_RCT_F_FK" FOREIGN KEY
	("SERVICE_FEES_ID")
	REFERENCES "SOA_LBR_RCT_FEES"
	("SERVICE_FEES_ID");

COMMENT ON COLUMN "SOA_ RCT_ RQS_PROF"."APPLICATION_NO" IS
'Application Number Part of the Unique Identifier of the Application , Unique within a given year .  ';

COMMENT ON COLUMN "SOA_ RCT_ RQS_PROF"."GENDER" IS
'Code For Gender .
1= Male
2= Female
';

COMMENT ON COLUMN "SOA_ RCT_ RQS_PROF"."NATIONALITY_ID" IS
'Code of Nationality Based on MOI Coding .';

COMMENT ON COLUMN "SOA_ RCT_ RQS_PROF"."PROFESSION_ID" IS
'Code of Profession Based on MOI Coding .';

COMMENT ON COLUMN "SOA_ RCT_ RQS_PROF"."REQUIRED_COUNT" IS
'The requested number of workers .';

COMMENT ON COLUMN "SOA_ RCT_ RQS_PROF"."YEAR" IS
'The YEAR when application has been submitted Part of the Unique Identifier of the Application.';

COMMENT ON COLUMN "SOA_ RCT_APV_ PROF"."APPLICATION_NO" IS
'Application Number Part of the Unique Identifier of the Application , Unique within a given year .  ';

COMMENT ON COLUMN "SOA_ RCT_APV_ PROF"."APPROVED_COUNT" IS
'The Approved  number of workers .';

COMMENT ON COLUMN "SOA_ RCT_APV_ PROF"."GENDER" IS
'Code For Gender .
1= Male
2= Female
';

COMMENT ON COLUMN "SOA_ RCT_APV_ PROF"."NATIONALITY_ID" IS
'Code of Nationality Based on MOI Coding .';

COMMENT ON COLUMN "SOA_ RCT_APV_ PROF"."PROFESSION_ID" IS
'Code of Profession Based on MOI Coding .';

COMMENT ON COLUMN "SOA_ RCT_APV_ PROF"."YEAR" IS
'The YEAR when application has been submitted Part of the Unique Identifier of the Application.';

COMMENT ON COLUMN "SOA_ RCT_CSR_REV"."APPLICATION_NO" IS
'Application Number Part of the Unique Identifier of the Application , Unique within a given year .';

COMMENT ON COLUMN "SOA_ RCT_CSR_REV"."NOTIFICATION" IS
'Text of the Message Communicated to end user using SMS , Email.';

COMMENT ON COLUMN "SOA_ RCT_CSR_REV"."NOTIFICATION_LANG" IS
'Language Code of  the Message Communicated to end user using SMS .
0 for English 
8 for Arabic
';

COMMENT ON COLUMN "SOA_ RCT_CSR_REV"."REMARK" IS
'To Communicate message between CSR and End User.';

COMMENT ON COLUMN "SOA_ RCT_CSR_REV"."RESULT" IS
'CSR Decision  about accept receiving the Application , Or Rejecting it , Or put it on hold  
1-Accepted
2-Rejected
3-Pending
';

COMMENT ON COLUMN "SOA_ RCT_CSR_REV"."REVIEW_DATE" IS
'CSR Review Date';

COMMENT ON COLUMN "SOA_ RCT_CSR_REV"."USER_ID" IS
'CSR USER ID as Registered with ICT .';

COMMENT ON COLUMN "SOA_ RCT_CSR_REV"."YEAR" IS
'The YEAR when application has been submitted Part of the Unique Identifier of the Application.';

COMMENT ON COLUMN "SOA_LBR_ NAT"."NAME_AR" IS
'Arabic Description .';

COMMENT ON COLUMN "SOA_LBR_ NAT"."NAME_EN" IS
'English Description .';

COMMENT ON COLUMN "SOA_LBR_ NAT"."NATIONALITY_ID" IS
'Code of Nationality Based on MOI Coding .';

COMMENT ON COLUMN "SOA_LBR_EST_PERSON_INFO"."NATIONALITY_ID" IS
'Code of Nationality Based on MOI Coding .';

COMMENT ON COLUMN "SOA_LBR_EST_PROF_STATISTICS"."NATIONALITY_ID" IS
'Code of Nationality Based on MOI Coding .';

COMMENT ON COLUMN "SOA_LBR_EST_PROF_STATISTICS"."PROFESSION_ID" IS
'Code of Profession Based on MOI Coding .';

COMMENT ON COLUMN "SOA_LBR_PROF"."NAME_AR" IS
'Arabic Description .';

COMMENT ON COLUMN "SOA_LBR_PROF"."NAME_EN" IS
'English Description .';

COMMENT ON COLUMN "SOA_LBR_PROF"."PROFESSION_ID" IS
'Code of Profession Based on MOI Coding .';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."ACTIVE_APP" IS
'This is a derived flag which indicates whether an application is active or not. For selecting active application, this flag must be considered in the WHERE clause of the SQL statement. 1=Active App
0=not Active App
';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."AGENT_EMAIL" IS
'Establishment  Agent EMAIL';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."AGENT_MOBILE" IS
'Establishment  Agent MOBILE number';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."AGENT_QID" IS
'Establishment  Agent QID';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."APPLICATION_DATE" IS
'Date Of Application Submission';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."APPLICATION_NO" IS
'Application Number Part of the Unique Identifier of the Application , Unique within a given year . ';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."ELECTRICITY_NO" IS
'ELECTRICITY Number As defined by KAHRAMA';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."EST_ID" IS
'Establishment ID Unique Identifier as Defined By MOI . ';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."REMARKS" IS
'General Remarks added as a place holder to communicate with End User extra info.';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."STATUS_ID" IS
'Application Status in different stages.';

COMMENT ON COLUMN "SOA_LBR_RCT_APP"."YEAR" IS
'The YEAR when application has been submitted Part of the Unique Identifier of the Application .';

COMMENT ON COLUMN "SOA_LBR_RCT_STATUS"."STATUS_AR" IS
'STATUS Arabic Description .';

COMMENT ON COLUMN "SOA_LBR_RCT_STATUS"."STATUS_EN" IS
'STATUS English Description .';

COMMENT ON COLUMN "SOA_LBR_RCT_STATUS"."STATUS_ID" IS
'Code Of The Of Application Valid Status ';

COMMENT ON TABLE "SOA_LBR_RCT_STATUS" IS
'10	????? ?? ???? ???	 
20	????? ??? ???????	 
30	????? ????? ???? ?? ????? ?????????  ? ?? ?????? ???? ??????	 
40	????? ????? ?? ????? ?????????	 
50	????? ????? ???? ?? ???? ?????????	?? ??? ?????? ???? ????? ?????? ??????? ??????? ?????
60	????? ????? ?? ???? ?????????	 
210	?? ?????? ???? ?????? ?????	 
220	?? ???  ?????? ?????	 
230	?????? ????? ???? ???? ??????? ?????????	 
';

